### ISSUE TITLE
Chart breaking when changing from 2 different devices simultaneously

### ISSUE THREAD

**Issue by johndevor** [convergencelabs/javascript-examples#2]
I think this resulted when I was dragging the sliders simultaneously on two separate devices. 

```
convergence-all.js:305 The model with id 'chart' was forcefully closed by the server: The commited version (3165) was not what was expected (3161).
t.vd @ convergence-all.js:305
76convergence-all.js:304 Uncaught Error: Can not perform actions on a detached RealTimeElement.
    at t.Wb (convergence-all.js:304)
    at t.Rb (convergence-all.js:304)
    at t.value (convergence-all.js:304)
    at RealtimeChart.<anonymous> (chart.js:75)
    at nouislider.js:1269
    at Array.forEach (<anonymous>)
    at nouislider.js:1267
    at Array.forEach (<anonymous>)
    at fireEvent (nouislider.js:1262)
    at move (nouislider.js:1382)
```

After this initial break, the example doesn't work consistently any more. A refresh causes it to work only temporarily (a second or so).

**Comment by mmacfadden** [comment]
Thanks for reporting the issue.

The real error is the first one. The second error is simply stating that the RealTimeModel resulting in the RealTimeElement being detached from the server, meaning you can't make changes. We can clean up the example a bit so that if it becomes disconnected it doesn't try to sync changes.

We will take a look to see why the app is getting disconnected in the first place.

**Comment by mmacfadden** [comment]
This has been fixed!
